version: "2"
services:
  lb:
    image: plone/plone-haproxy
    depends_on:
    - backend
    ports:
    - "80:8080"
    - "1936:1936"
    environment:
      FRONTEND_PORT: "8080"
      BACKENDS: "backend"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      INTER: "5s"
      LOG_LEVEL: "info"
  backend:
    image: plone/plone-backend
